# Introduction
Numpy is a linear algebra library

In [4]:
#To install
conda install numpy # If you use anaconda environment management
pip install numpy # If you use the pip package manager

SyntaxError: invalid syntax (2868764268.py, line 3)

In [5]:
import numpy as np

# Arrays

In [6]:
# Creating numpy arrays from python list
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# Build-in methods to generate Arrays

# arange: Return evenly spaced values within a given interval
np.arange(0,10)
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
# zeros and ones
np.zeros(3)
np.zeros((2,2))

np.ones(5)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# linspace: Return evenly spaced numbers over a specified interval
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
# eye: Creates an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
# Random: Creates random number array

# rand: Create an array of given shape and populate it with random samples from a uniform distribution [0,1]
np.random.rand(2)

# randn: Return a sample(or samples) from "standard normal" distribution. Unlike rand which is uniform
np.random.randn(7)

# randint: Return random integers from low(inclusive) to high(exclusive)
np.random.randint(1,100)
np.random.randint(1,100,10)

array([ 4, 72, 13, 37, 55,  7, 48, 69, 13, 14])

In [30]:
# Array attributes and methods

# reshape: Returns an array containing the same data with a new shape
arr = np.arange(25)
arr.reshape(5,5)

# Methods for finding values
arr.max() # Max value
arr.min() # Min value
arr.argmax()
arr.argmin()

# dtype: Grab the data type of the object in the array
arr.dtype

dtype('int64')

# Indexing and selection

In [31]:
# Bracket indexing and selection
arr[8]

arr[1:5]

array([1, 2, 3, 4])

In [42]:
# Broadcasting: Numpy arrays differ from normal python lists because of their ability to 
# broadcast(Setting a value with index range)
arr = np.arange(0,11)
arr[0:5] = 100

matrix = [[1,2,3],[4,5,6],[7,8,9]]
array_2d = np.array(matrix)
array_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [43]:
# Selection

arr = np.arange(1,11)
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [44]:
bool_arr = arr > 4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

# Operations

In [49]:
arr = np.arange(1,10)

# Sum
arr + arr

# Mulplication
arr * arr

# Sub
arr - arr

# Division
arr/arr

# Exponent
arr *3 

# Square root
np.sqrt(arr)

# Exponent
np.exp(arr)

# Sum maxs
np.max(arr)

# Sen
np.sin(arr)

# log
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])